vscode:
    extensions:
        - ms-vscode.cpptools@0.26.2:Pq/tmf2WN35SanVzB4xZc1g==
tasks:
- init: >
    mkdir \build &&
    cd \build &&
    cmake -D CMAKE_EXPORT_COMPILE_COMMANDS=ON .. &&
    make
    
